version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
        - "127.0.0.1:9090:9090"
    links:
      - alertmanager:alertmanager
    networks:
      - back-tier

  graphite-exporter:
    container_name: graphite-exporter
    image: prom/graphite-exporter
    volumes:
        - ./graphite-exporter/:/etc/graphite-exporter/
    command: '-graphite.mapping-config=/etc/graphite-exporter/graphite_mapping.conf -graphite.sample-expiry 1h'
    ports:
        - "10.8.0.10:2003:9109"
    expose:
        - 9108
    networks:
      - back-tier

  alertmanager:
    image: prom/alertmanager
    ports:
        - "127.0.0.1:9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
        - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
